name: Deploy Web Project to Vercel

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    name: Deploy Web Project to Vercel
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install Dependencies
        run: pnpm install  # Or use pnpm or another package manager

      - name: Build Web Project
        run: pnpm run build 

      - name: Install Vercel CLI
        run: pnpm install -g vercel

      - name: Login to Vercel
        run: pnpml login --token ${{ secrets.VERCEL_TOKEN }}

      - name: Deploy to Vercel
        run: pnpm --prod --confirm --scope My Team --dir /apps/web/.next
